version: '3.8'

services:
  system-tests:
    image: system-tests
    container_name: system-tests
    volumes:
      - ./tests/data:/app/hg_ref
    environment:
      - GRCH37_FASTA=/app/hg_ref/chr21_grch37.fa.gz
      - GRCH38_FASTA=/app/hg_ref/chr21_grch38.fa.gz
    build:
      context: .
      target: tests
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5001/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["pytest"]
