version: '3.8'
services:
  spliceaiapi:
    image: schnknc/spliceaiapi:latest
    container_name: spliceaiapi_container
    volumes:
      - type: bind
        source: ~/Projects/genome_references
        target: /hg_ref
    environment:
      GRCH37_FASTA: "/hg_ref/b37/human_g1k_v37.fasta"
      GRCH38_FASTA: "/hg_ref/hg_ref/Homo_sapiens_assembly38.fasta"
      ENSEMBL_TIMEOUT: "120"
    ports:
      - "5001"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx:/etc/nginx/conf.d # Map your NGINX config folder to the container
    ports:
      - "80:80"
    depends_on:
      - spliceaiapi
    restart: unless-stopped
