name: Prepare Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prepare-docker-image:
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
      
    - name: Generate version number
      id: tag_version
      uses: anothrNick/github-tag-action@1.70.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 1.0.0

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images:  ${{ vars.DOCKERHUB_USERNAME }}/spliceaiapi
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}