name: Create Release for AMD64 + ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # 1) Generate a single version from the "anothrNick/github-tag-action"
  get-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Generate version number
        id: tag_version
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      
      - name: Output version number
        run: echo "Tag is ${{ steps.tag_version.outputs.tag }}"

  # 2) Build & push per-architecture images (two parallel jobs in a matrix).
  build-and-push:
    needs: get-version
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        env:
          USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          REPOSITORY: spliceaiapi
          TAG_LATEST: latest
          TAG_SEMVER: ${{ needs.get-version.outputs.tag }}
          TAG_SHA: ${{ github.sha }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          # Use the env.* syntax for each environment variable.
          tags: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ env.TAG_LATEST }},
                ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ env.TAG_SEMVER }},
                ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ env.TAG_SHA }}

  # 3) Create a GitHub release after pushing images
  create-release:
    needs: [get-version, build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.get-version.outputs.tag }}
          generateReleaseNotes: true