name: Test Docker build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        show-progress: 'false'

    - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Copy test FASTA files (chr21) to hg_ref folder for testing
      run: |
        ./copy_small_fasta.sh
        
    - name: Run Tests
      run: ./run-system-tests.sh