name: Test Docker build for AMD64 + ARM64

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Print runner architecture info
        run: |
          echo "Running on: ${{ runner.os }} (architecture: ${{ runner.arch }})"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy test FASTA files
        run: ./copy_small_fasta.sh

      - name: Determine Docker platform
        id: arch
        run: |
          if [ "${{ runner.arch }}" = "X64" ]; then
            echo "ARCH=amd64" >> $GITHUB_OUTPUT
          elif [ "${{ runner.arch }}" = "ARM64" ]; then
            echo "ARCH=arm64" >> $GITHUB_OUTPUT
          else
            # Fallback if there's another arch
            echo "ARCH=amd64" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/${{ steps.arch.outputs.ARCH }} \
            --target tests \
            -t system-tests:${{ steps.arch.outputs.ARCH }} \
            --load \
            .

      - name: Run system tests
        run: ./run-system-tests.sh